apiVersion: v2
name: adguard-home-ocp
description: AdGuard Home chart optimized for OpenShift 
icon: https://raw.githubusercontent.com/Wiesmak/adguard-home-ocp/refs/heads/master/icon.svg


type: application

version: 0.1.0

appVersion: "0.107.71"
